### ISSUE TITLE
Paris datase: Number of scales in training does not correspond number of scales in evaluation

### ISSUE THREAD

**Issue by eladmeir** [shellysheynin/HTDG-model#3]
I have been playing with this repo for a while now, and could train both CIFAR, and MNIST, with great evaluation performance.

The problem is in the Paris dataset (DataLoader, maybe?) - while it produces 5 scales in training (0-4), as for MNIST and CIFAR. I expect it to evaluate on these scales, and only these (0-4)

The problem is that while I am trying to evaluate Paris dataset - it looks for a 6th scale (6) and thus crashes (couldn't find the 6th pth file)

The fix might be very simple, but first I want to make sure that I am not missing something.

Does anyone have any insights about this issue?

**Comment by cnmcnm111** [comment]
I think  maybe you can try to chage the '--test_size'.

**Comment by eladmeir** [comment]
Hey @cnmcnm111 
Thanks for the reply, but I am wayyyyyyyyyyyy over this repo. I was working on it 2.5 years ago and can't even remember if or where I was using it for...

Thanks, I will close it
